### ISSUE TITLE
Consistently getting errors

### ISSUE THREAD

**Issue by Tomagori** [noobj2/Anki-Review-PopUp#14]
This addon works and it's awesome, however, every 20 or so cards, I get the following error:

```
  Error 
  An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
  If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
  When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
  Debug info:
  Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
  Platform: Windows 10
  Flags: frz=True ao=True sv=2
  Add-ons, last update check: 2021-10-19 09:33:32
  
  Caught exception:
  Traceback (most recent call last):
    File "aqt\webview.py", line 526, in handler
    File "aqt\reviewer.py", line 544, in _onTypedAnswer
    File "<decorator-gen-10>", line 2, in _showAnswer
    File "anki\hooks.py", line 89, in decorator_wrapper
    File "anki\hooks.py", line 81, in repl
    File "C:\Users\Christoph\AppData\Roaming\Anki2\addons21\976516370\ShowAnswer_PopUp.py", line 34, in myPopUp
      audio_name = '/{}'.format(random.choice(audioName_list))
    File "random.py", line 290, in choice
  IndexError: Cannot choose from an empty sequence
```

If I understand that correctly, it wants to play/show whatever is in "show_answer", but the corresponding folder is empty (I have no use for it). However, it shouldn't trigger ShowAnswer in the first place, as "Show Answer Pop-Up Chance" is set to 0%.

**Comment by noobj2** [comment]
the add-on chooses the audio before checking whether the pop up chance is 0 -\_- and then after choosing it, if pop up chance is 0% then it won't play
if the audio folder is not empty, it won't have a problem -\_- so you can add an audio file inside the folder until a publish a fixed version of the add-on

and thanks for the report ;) I really appreciate it
